version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - wsl
  settings:
    dogsled:
      max-blank-identifiers: 3
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - golint
        text: comment on exported var
      - linters:
          - golint
        text: don't use an underscore in package name
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - wsl
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
